### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [mengxu98/inferCSN#12]
@mengxu98: This package fails its checks for the release candidate for igraph 2.0.0. See <https://github.com/igraph/rigraph/blob/igraph-0.10/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

It's likely that the problems are related to https://github.com/briatte/ggnetwork/issues/74, which has been fixed on GitHub but hasn't found its way to CRAN yet.

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph@igraph-0.10")` .

We're planning to release igraph 2.0.0 just before CRAN's closing on Christmas. This should give us at least until mid-January to resolve this and keep CRAN happy at the same time. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by mengxu98** [comment]
@krlmlr Thank you for this issue.  I'm eagerly anticipating the arrival of igraph 2.0.0.

I tested my package by referencing the information provided here: https://github.com/igraph/rigraph/blob/igraph-0.10/revdep/problems.md. Using `pak::pak("igraph/rigraph@igraph-0.10")`, I installed the igraph 2.0.0 release candidate and didn't encounter the problem mentioned. I believe the issue has been resolved with the update to ggnetwork.

**Comment by krlmlr** [comment]
Thanks. I still see ggnetwork 0.5.12 on CRAN and in `available.packages()` . Are you using the development version of ggnetwork? Does this behavior change when you switch to the CRAN version?

**Comment by mengxu98** [comment]
Thank you, I tested the CRAN version and the version on GitHub for ggnetwork again, and both results were normal.

**Comment by krlmlr** [comment]
Thanks, checking again on our infrastructure.

**Comment by mengxu98** [comment]
Thank you very much.

**Comment by krlmlr** [comment]
Still seeing the same problems on our infrastructure.

Can you please try with a clean package library? Is this problem perhaps fixed on the main branch of this repo, but not yet on CRAN?

**Comment by mengxu98** [comment]
I will test the method you provided, thanks.

**Comment by krlmlr** [comment]
New anticipated release data: January 12.

**Comment by krlmlr** [comment]
We're planning to send igraph to CRAN on January 23, we're still seeing failures with this package: https://github.com/igraph/rigraph/blob/main/revdep/problems.md .
